version: '3'

services:
  mysql-docker-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Root@1234
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=Demo@1234
    volumes:
      - /data/mysql
  cqrs-example-docker-compose-app:
    image: cqrs-example-docker-compose-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8082:8080
    volumes:
      - /data/cqrs-example-docker-compose-app